# This script is meant to be run from the root of the zyn-fusion-build repo.
# It builds ZynFusion's tarballs for Ubuntu and Windows (cross-build).

# Uncomment this line if your system requires sudo to run docker.
#SUDO=sudo

# Version number included in the tarballs generated by the build process.
# It must match the version number at the top of Common.mk.
# This is required because 'docker cp' doesn't support wildcards.
ZYNADD_VERSION=$(cat ./version.txt)

# Optional: pin zynaddsubfx/zest to a specific commit/branch instead of the
# latest master (see ZYNADDSUBFX_COMMIT/ZEST_COMMIT defaults in Common.mk).
# ZYNADDSUBFX_COMMIT=d3b3abd08c42333a95bbaa44214336fe0b7a2437 is working as of 2024-06-05, but newer commits may break the build.
ZYNADDSUBFX_COMMIT=${ZYNADDSUBFX_COMMIT:-}
ZEST_COMMIT=${ZEST_COMMIT:-}

#### No user parameters below this line ####
set -e
DOCKER="docker"

# Base image for cross-compilation Windows builds
${DOCKER} rmi --force zf-ubuntu-w64-img ||:
${DOCKER} build -t zf-ubuntu-w64-img -f docker-builders/ubuntu-windows.dockerfile .

# Cross-compilation release
${DOCKER} rm --force zf-ubuntu-w64 ||:
${DOCKER} run -d --name zf-ubuntu-w64 zf-ubuntu-w64-img sleep infinity
${DOCKER} cp z/windows-build.cmake zf-ubuntu-w64:/z/z/.
${DOCKER} cp $0 zf-ubuntu-w64:/z/build.sh

MAKE_VARS="${ZYNADDSUBFX_COMMIT:+ZYNADDSUBFX_COMMIT=${ZYNADDSUBFX_COMMIT}} ${ZEST_COMMIT:+ZEST_COMMIT=${ZEST_COMMIT}}"

# First pass: builds zynaddsubfx, then starts Zest, which builds its bundled
# libuv submodule (deps/libuv) and fails compiling it - that libuv redefines
# a struct that modern mingw-w64 headers already provide.
${DOCKER} exec zf-ubuntu-w64 make MODE=release PARALLEL=1 ${MAKE_VARS} -f Makefile.windows.mk || true

# NOTE: "ifndef SIO_TCP_INITIAL_RTO" already occurs (unrelatedly) in the
# unpatched file, guarding just the #define below - so it can't be used as
# the applied-marker, or this check always finds a false positive and skips.
${DOCKER} exec zf-ubuntu-w64 sh -c '
  F=/z/src/mruby-zest-build/deps/libuv/src/win/winapi.h
  if [ -f "$F" ] && ! grep -q "zyn-fusion-build: mingw64 already provides this" "$F"; then
    sed -i "/\/\* From mstcpip.h \*\//a #ifndef SIO_TCP_INITIAL_RTO /* zyn-fusion-build: mingw64 already provides this */" "$F"
    sed -i "/# define  SIO_TCP_INITIAL_RTO _WSAIOW(IOC_VENDOR,17)/a #endif" "$F"
  fi
'

# Second pass: resume from zest/package only, since zynaddsubfx already succeeded.
${DOCKER} exec zf-ubuntu-w64 make MODE=release PARALLEL=1 ${MAKE_VARS} -f Makefile.windows.mk zest package

${DOCKER} exec -e ZYNADD_VERSION="${ZYNADD_VERSION}" zf-ubuntu-w64 sh -c '
  set -e
  cd /z/build
  DIR="zyn-fusion-windows-64bit-${ZYNADD_VERSION}-release"
  rm -rf "$DIR"
  unzip -q "$DIR.zip"
  cp /z/build.sh "$DIR/build.sh"
  {
    echo "=== zynaddsubfx ==="
    git --no-pager -C /z/src/zynaddsubfx log -1 --format="%H %ad %s" --date=short
    echo
    echo "=== zest (mruby-zest-build) ==="
    git --no-pager -C /z/src/mruby-zest-build log -1 --format="%H %ad %s" --date=short
    echo
    echo "=== Dependencies ==="
    for f in /z/download/*.tar.gz /z/download/*.tgz; do [ -e "$f" ] && basename "$f"; done
    printf "libuv (Zest submodule): "
    git --no-pager -C /z/src/mruby-zest-build/deps/libuv log -1 --format="%H %ad %s" --date=short
    echo
    echo "=== Toolchain ==="
    (. /etc/lsb-release 2>/dev/null && echo "Built on: $DISTRIB_DESCRIPTION") \
      || echo "Built on: Debian $(cat /etc/debian_version)"
    x86_64-w64-mingw32-gcc --version | head -1
    echo
    echo "=== zyn-fusion-build ==="
  } > "$DIR/BUILDINFO.txt"
'

# zyn-fusion-build itself is not a git checkout inside the container (the
# Dockerfile only COPYs individual tracked files, not .git), so its own
# commit info has to be captured on the host and piped in.
git log -1 --format="%H %ad %s" --date=short | \
  ${DOCKER} exec -i -e ZYNADD_VERSION="${ZYNADD_VERSION}" zf-ubuntu-w64 sh -c \
    'cat >> "/z/build/zyn-fusion-windows-64bit-${ZYNADD_VERSION}-release/BUILDINFO.txt"'

${DOCKER} exec -e ZYNADD_VERSION="${ZYNADD_VERSION}" zf-ubuntu-w64 sh -c '
  cd /z/build
  DIR="zyn-fusion-windows-64bit-${ZYNADD_VERSION}-release"
  rm -f "$DIR.7z"
  # NOTE: pass the directory itself, not a "$DIR"/* glob - 7z (unlike zip)
  # strips the common-prefix directory from globbed args, flattening the
  # archive instead of nesting everything under "$DIR/".
  7z a -bd -mx=9 "$DIR.7z" "$DIR" > /dev/null
  rm -rf "$DIR" "$DIR.zip"
'

${DOCKER} cp zf-ubuntu-w64:/z/build/zyn-fusion-windows-64bit-${ZYNADD_VERSION}-release.7z .
${DOCKER} rm --force zf-ubuntu-w64

# Cleanup
${DOCKER} rmi zf-ubuntu-w64-img

# The BUILDINFO/ZYNFUSION_BUILD_COMMIT provenance files only record the last
# commit, so warn if there are uncommitted changes that wouldn't show up there.
if ! git diff --quiet || ! git diff --cached --quiet || [ -n "$(git ls-files --others --exclude-standard)" ]; then
  echo "WARNING: git working tree is not clean; build provenance may not reflect the actual build inputs." >&2
  git status --short
else
  echo "Git working tree is clean; build provenance should reflect the actual build inputs."
fi
